apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- pv-claims.yml

namespace: development

patchesStrategicMerge:
- configmap.yml
- ingress.yml
- app.yml

# Use replacements to swap out the PVC names in the app deployment
replacements:
- source:
    kind: PersistentVolumeClaim
    name: development
  targets:
  - select:
      kind: Deployment
      name: taxonworks
    fieldPaths:
    - spec.template.spec.volumes.[name=taxonworks-media-vol].persistentVolumeClaim.claimName
    - spec.template.spec.volumes.[name=taxonworks-backup-vol].persistentVolumeClaim.claimName
    - spec.template.spec.volumes.[name=taxonworks-staging-vol].persistentVolumeClaim.claimName
