---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: development
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  # storageClassName: standard  # Uncomment and set your AKS storage class