# Remove the individual PVCs since we're using shared-dev-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taxonworks-media-pv-claim
$patch: delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taxonworks-backup-pv-claim
$patch: delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taxonworks-staging-pv-claim
$patch: delete