apiVersion: v1
kind: ConfigMap
metadata:
  name: taxonworks
data:
  # Override server configuration for experimental environment
  server.name: "taxonworks.48.216.156.172.sslip.io"
  
  # Override email configuration
  tw.exception_notification.sender_address: "wbbaker@purdue.edu"
  tw.exception_recipients: "wbbaker@purdue.edu"
  
  # Override SMTP configuration
  tw.action_mailer_smtp_settings.address: "smtp.purdue.edu"
  tw.action_mailer_smtp_settings.domain: "purdue.edu"
  tw.action_mailer_url_host: "taxonworks.48.216.156.172.sslip.io"
  tw.mail_domain: "purdue.edu"