apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taxonworks

  # - namespace.yml  # Commented out for AKS - namespace managed separately
resources:
- configmap.yml
- secret.yml
- postgres.yml
- pv-claims.yml
- app.yml
- ingress.yml

images:
- name: sfgrp/taxonworks
  newTag: 0.9.8
